### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by davephillips** [mharju/VCV-Evaluator#1]
Fedora 23 Linux
Rack master (0.6.x)

Greetings ! I'm trying to build your module for Linux but I've hit a couple easily resolved errors and one show-stopper. The easy ones were path errors: For Linux (well, for Fedora 23) the headers for chicken Scheme (4.11, btw) are installed at /usr/include/chicken, so I reset the includes for ElasticOrange.cpp and ElasticOrange.hpp from simply chicken.h to chicken/chicken.h. The build proceeds until this error:

[dlphilp@The6300 VCV-Evaluator]$ make
g++  -Wsuggest-override -std=c++11 -I/usr/local/Cellar/chicken/4.13.0/include/chicken -fPIC -I../../include -I../../dep/include -DSLUG=ElasticOrange-Evaluator4x4 -DVERSION=0.6.0dev -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/Evaluator.cpp.o src/Evaluator.cpp
g++  -Wsuggest-override -std=c++11 -I/usr/local/Cellar/chicken/4.13.0/include/chicken -fPIC -I../../include -I../../dep/include -DSLUG=ElasticOrange-Evaluator4x4 -DVERSION=0.6.0dev -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/ElasticOrange.cpp.o src/ElasticOrange.cpp
csc -C  src/engine.scm -emit-external-prototypes-first -c -o build/engine.scm.o
csc: no source files specified
Makefile:31: recipe for target 'build/engine.scm.o' failed
make: *** [build/engine.scm.o] Error 64

I worked with Scheme a long time ago, mostly with Rick Taube's Common Music, but I'm not familiar with Chicken Scheme. Is the nrepl-library package available for Linux ?

**Comment by mharju** [comment]
Hi! Currently I've only been running this in OS X. Nrepl-library should be available as an Egg via `chicken-install nrepl`.

That error message is a bit strange though, can you check csc is actually the chicken scheme compiler? I have Chicken Scheme version 4.13.0 on my end.

**Comment by davephillips** [comment]
Thanks for your reply ! A few more notes. I figured out that I can set the paths in the Makefile, so I've left the includes as you added them (in ElasticOrange.*pp). I also deleted the repo version of Chicken Scheme, then built and installed 4.13.0 myself. I also successfully retrieved nrepl as per your instructions. Here's the output from csc -version:

$ csc -version
(c) 2008-2017, The CHICKEN Team
(c) 2000-2007, Felix L. Winkelmann
Version 4.13.0 (rev 68eeaaef)
linux-unix-gnu-x86-64 [ 64bit manyargs dload ptables ]
compiled 2017-12-11 on yves.more-magic.net (Linux)

Enter `chicken -help' for information on how to use the compiler,
or try `csc' for a more convenient interface.

Run `csi' to start the interactive interpreter.

Alas, I still get the same error when trying to build your module:

$ make
/usr/local/bin/csc -C src/engine.scm -emit-external-prototypes-first -c -o build/engine.scm.o
csc: no source files specified
Makefile:32: recipe for target 'build/engine.scm.o' failed
make: *** [build/engine.scm.o] Error 64

I think some friends in the Csound group have experience with Chicken Scheme, I'll check with them to see if they can help figure what's going wrong.

**Comment by davephillips** [comment]
Salutations ! I've successfully built and loaded your module into the latest Rack master git pull. I'd like to run the example quant.scm file, can you walk me through the process ? I have vim installed (it's my favorite text editor), hopefully that will help. :)

Btw, the -C option needed changed to -c, that's why csc didn't see the source file. I also needed to build chicken scheme 4.13.0 with the -fPIC option added to the CFLAGS.

**Comment by mharju** [comment]
So, to get quant.scm loaded, just add the module to VCV, and connect to the REPL at `localhost:4000` and copy-paste the content there. I just use `rlwrap nc localhost 4000` myself. I made a quick demo about it on YouTube, see if that helps!

I'll push the version I'm using in the video shortly.

Oh, the -C option actually was passing `$(MAC_SDK_FLAGS)` to it, and they are missing in Linux. I'll improve that at some point. You can just remove that on your side if you want and just use:
`csc src/engine.scm -emit-external-prototypes-first -c -o build/engine.scm.o`

[Evaluator on YouTube](https://www.youtube.com/watch?v=j5eDIYiFLXo)

**Comment by davephillips** [comment]
Hey, it works ! Thanks for the new example, that got me going much better than the first one. I used the patch as seen in your YT video, works perfectly now though I do get some occasional glitchy audio. I'm running Jack at 48k with a relatively small buffer, that may impact the patch performance, but please advise if you can suggest any particular optimization.

Nice work on this module. It's fun to reconnect with Scheme, I liked the language a lot in Common Music. I wonder if I can run some code from CM with the module. Hmm, I'll have to give it a try.

**Comment by mharju** [comment]
Good to hear! I'm also experiencing some performance issues, I managed to mostly get around them by increasing the buffer size. I think they have to do with chicken's garbage collection (or the fact that the code is not compiled but interpreted), but am not totally sure.

This module was mainly just an idea I wanted to try out, nice to hear there are others who think this is cool too!

**Comment by mharju** [comment]
@davephillips Could you try to do `csc -dynamic quant.scm` and move the .so -file to the root of Rack, and say `(load "quant")` at the REPL and tell if it makes any difference to you performancewise? Thanks!

**Comment by davephillips** [comment]
Wow, it makes a huge difference. Performance was completely clean, no breakup of the audio at all.

**Comment by mharju** [comment]
OK! So it seems that it would be beneficial to compile (at least some?) of the stuff before loading it in. What I discovered was that if I load it again, it won't reload but if I give the `.so` a different filename every time, it reloads.

I'll look into this a bit when I have some spare time :)
