### ISSUE TITLE
Crash at compilting (Windows)

### ISSUE THREAD

**Issue by caecos** [mharju/VCV-Evaluator#2]
$ make
g++  -Wsuggest-override -std=c++11 -I/usr/local/Cellar/chicken/4.13.0/include/chicken -DSLUG=ElasticOrange-Evaluator4x4 -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0dev -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/ElasticOrange.cpp.o src/ElasticOrange.cpp
In file included from src/ElasticOrange.cpp:1:0:
src/ElasticOrange.hpp:2:10: fatal error: chicken.h: No such file or directory
 #include <chicken.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [../../compile.mk:65: build/src/ElasticOrange.cpp.o] Error 1

**Comment by mharju** [comment]
You need Chicken Scheme to compile this project. See instructions at http://code.call-cc.org/

**Comment by caecos** [comment]
I've tried but that does not work...can you compile a binary for Windows?

**Comment by mharju** [comment]
Unfortunately I don't have a windows at hand, so sorry no :( You also need the nrepl package from 
`chicken-install`. Check that you have the header & library files for chicken in your `PATH`

**Comment by caecos** [comment]
Ok thx

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
